server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/olist}
    username: ${SPRING_DATASOURCE_USERNAME:olist}
    password: ${SPRING_DATASOURCE_PASSWORD:olist}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: warn
app:
  jwt-secret: "portfolio-demo-secret-key-change-me-please-32chars"
